// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Xz_urc4bnDHxDUZiM1pLVORnI04Mll8',
    appId: '1:644394627702:web:11e263167297b11a9c2557',
    messagingSenderId: '644394627702',
    projectId: 'expensetracker-3da54',
    authDomain: 'expensetracker-3da54.firebaseapp.com',
    storageBucket: 'expensetracker-3da54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUGeG8D3P-KbPGBth1lHw6Nxm7OG1R7U0',
    appId: '1:644394627702:android:cb91be7266f798619c2557',
    messagingSenderId: '644394627702',
    projectId: 'expensetracker-3da54',
    storageBucket: 'expensetracker-3da54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJYS8ZXtzsPpnSWDk0AWUNrzBHg8EwcyM',
    appId: '1:644394627702:ios:90528a1c9492b1f39c2557',
    messagingSenderId: '644394627702',
    projectId: 'expensetracker-3da54',
    storageBucket: 'expensetracker-3da54.appspot.com',
    iosClientId: '644394627702-89b2ngrga3b0iu61uqdhqelf50jgqe4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJYS8ZXtzsPpnSWDk0AWUNrzBHg8EwcyM',
    appId: '1:644394627702:ios:90528a1c9492b1f39c2557',
    messagingSenderId: '644394627702',
    projectId: 'expensetracker-3da54',
    storageBucket: 'expensetracker-3da54.appspot.com',
    iosClientId: '644394627702-89b2ngrga3b0iu61uqdhqelf50jgqe4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
